name: Deploy Prod Chelterinho API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build project
        run: npm run build

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t diegoseven/clubinho-api:prod -f DockerFile .

      - name: Push Docker image
        run: docker push diegoseven/clubinho-api:prod

  deploy:
    needs: build
    runs-on: [self-hosted, production]
    steps:
      - name: Start Docker if not running
        run: sudo systemctl start docker

      - name: Remove old container if exists
        run: |
          if sudo docker ps -a --format '{{.Names}}' | grep -Eq "^clubinho-api$"; then
            echo "ðŸ§¼ Removendo container antigo..."
            sudo docker rm -f clubinho-api
          else
            echo "âœ… Nenhum container antigo encontrado"
          fi

      - name: Remove old image if exists
        run: |
          if sudo docker images --format '{{.Repository}}:{{.Tag}}' | grep -q "^diegoseven/clubinho-api:prod$"; then
            echo "ðŸ§¼ Removendo imagem antiga..."
            sudo docker rmi -f diegoseven/clubinho-api:prod
          else
            echo "âœ… Nenhuma imagem antiga encontrada"
          fi

      - name: Pull new image from Docker Hub
        run: sudo docker pull diegoseven/clubinho-api:prod

      - name: Run new container
        run: |
          sudo docker run -d --restart=always -p 3000:3000 \
            -e ENVIRONMENT=${{ secrets.PROD_ENVIRONMENT }} \
            -e PORT=${{ secrets.PORT }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_NAME=${{ secrets.PROD_DB_NAME }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
            -e SES_DEFAULT_FROM=${{ secrets.PROD_SES_DEFAULT_FROM }} \
            -e SES_DEFAULT_TO=${{ secrets.PROD_SES_DEFAULT_TO }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }} \
            -e JWT_REFRESH_SECRET=${{ secrets.JWT_REFRESH_SECRET }} \
            -e JWT_REFRESH_EXPIRES_IN=${{ secrets.JWT_REFRESH_EXPIRES_IN }} \
            -e TWILIO_ACCOUNT_SID=${{ secrets.PROD_TWILIO_ACCOUNT_SID }} \
            -e TWILIO_AUTH_TOKEN=${{ secrets.PROD_TWILIO_AUTH_TOKEN }} \
            -e TWILIO_WHATSAPP_FROM=${{ secrets.PROD_TWILIO_WHATSAPP_FROM }} \
            -e TWILIO_WHATSAPP_TO=${{ secrets.PROD_TWILIO_WHATSAPP_TO }} \
            -e FEED_CLUBINHO_PAGE_ID=${{ secrets.PROD_FEED_CLUBINHO_PAGE_ID }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --name clubinho-api diegoseven/clubinho-api:prod
